- assoc.c
- doc/new_lru.txt
- doc/protocol.txt
- doc/threads.txt
- items.c
- items.h
- memcached.c
- memcached.h
- slabs.c
- slabs.h
- t/binary.t
- t/flush-all.t
- t/lru-maintainer.t
- t/refhang.t
- t/stats.t
- thread.c
This branch is a functional reworking of memcached's core LRU. Looking for some help with folks willing to run tests or try swapping a development or production machine to see if the hit ratio improves (or if it crashes).
Direct link to branch: https://github.com/dormando/memcached/tree/lru_rework - you can click "download zip" if you don't want a git clone. Build: `./autogen.sh && ./configure && make && make test` - need libevent-devel or equivalent installed.
* cache_lock is gone, LRU's are now independently locked.
* LRU's are now split between HOT, WARM, and COLD LRU's. New items enter the HOT LRU.
* LRU updates only happen as items reach the bottom of an LRU. If active in HOT, stay in HOT, if active in WARM, stay in WARM. If active in COLD, move to WARM.
* HOT/WARM each capped at 32% …
> [Work In Progress] LRU rework

- items.c
- memcached.c
- memcached.h
- slabs.c
- slabs.h
- t/binary.t
- t/chunked-items.t
- t/item_size_max.t
- t/slabs-reassign-chunked.t
Work in progress PR for chunked item support. As of writing this is largely functional, but is incomplete and may need a refactor.
---
* What is large item support?
Items have always required a single chunk large enough to hold its header, key, and data. This is done via a slab allocator, which is split into many sized slabs. The "largest available slab", became the largest item you could store into memcached. This is where the 1 megabyte limit came in.
The larger the item size limit, the less efficient the slab allocator is, as there is more space between slab classes.
With this change, the max slab chunk size is decoupled from the max item size, and items larger than the max chunk size now consist of multiple chunks chained together.
This has a number of benefits:
* Performance is …
> Chunked (large) item support

- LICENSE.itoa_ljust
- Makefile.am
- cache.c
- cache.h
- doc/protocol.txt
- items.c
- itoa_ljust.c
- itoa_ljust.h
- memcached.c
- memcached.h
- t/inline_asciihdr.t
- t/issue_42.t
This is a fun one. Since time forgotten, memcached has rendered the client flags and item byte size into the item itself (along with some spaces and \r\n). This is then directly streamed along with the item during the ASCII response. However, this leads to:
- Several sprintf's during SET's (checking the item size, storing the item)
- strtoul's and sprintf's during incr/decr/append/prepend
- strtoul's during binary protocol responses (turning the ASCII flags back into an integer)
- Useless sprintf's during binprot sets.
- Potentially significant memory overhead if you are trying to tightly pack very small items.
- GETS (cas get) has always done a funny inline sprintf anyway.
So this branch attempts to replace this with a very fast print routine. Much thanks to the author of the itoa …
> Make item-inlined ASCII response header optional

- crawler.c
- items.c
- items.h
- memcached.c
- memcached.h
- slabs.c
- thread.c
This series builds on top of the inline_asciihdr PR (https://github.com/memcached/memcached/pull/241)
For multigets and pipelined requests, the cumulative series can potentially be 13.5% faster. Starting from inline_asciihdr PR, with `-o modern -t 20` on a fairly large machine, and mc-crusher's mget test: (in millions of keys per second)
```
- baseline: 24.2m (no inline)
- + iov opt: 25.5m
- + inline LRU bump: 26.8m
- + bigger suffixlist: 26.9m - more consistent numbers
- + remove refcount atomics: 28m
```
With inline asciihdr responses enabled (vs dynamic as per the branch) the numbers go even higher. For single-key fetches, I could not measure a difference. Further improvements to the frontend pipeline could make more usage from these optimizations.
I keep putting off a major refactor …
> Frontend performance fixes

- doc/new_lru.txt
- doc/protocol.txt
- items.c
- items.h
- memcached.c
- memcached.h
- t/lru-maintainer.t
- util.c
- util.h
This PR is now complete. Will be doing separate PR's for further work.
Update 1) Now named "temporary" to hopefully be less confusing. Most major fixes done, should go for the bonus.
Update 2) Going to punt on inline reclaim. Will get better results from work elsewhere. This is ready for any reviews/tests before merging to next.
Update 3) Think I want to fine-tune this slightly more: There's another bug where promotion from probationary queue should get hit twice (is currently just once from cold), also I think re-linking within HOT is a poor usage of that space. Finally, hot|warm defaults of 32% were meant to be tuned and I don't want to flip this as a default without some kind of auto-tuning. I believe HOT -> 32% of memory or max-age of 3600s by default, WARM -> 32% of memory or max-age …
> LRU-2Q algorithm fixes

- doc/protocol.txt
- items.c
- memcached.c
- memcached.h
If LRU maintainer thread is started, this allows you to switch between "flat"
and "segmented" modes at runtime. The maintainer thread will drain HOT/WARM
LRU's if put into flat mode, and no new items should fill in.
This was much easier than expected...
> Allow switching LRU algo's at runtime

- items.c
- items.h
- memcached.c
- memcached.h
- slabs.c
- slabs.h
- t/slabs-reassign-chunked.t
Memory chunk chains would simply stitch multiple chunks of the highest slab
class together. If your item was 17k and the chunk limit is 16k, the item
would use 32k of space instead of a bit over 17k.
This refactor simplifies the slab allocation path and pulls the allocation of
chunks into the upload process. A "large" item gets a small chunk assigned as
an object header, rather than attempting to inline a slab chunk into a parent
chunk. It then gets chunks individually allocated and added into the chain
while the object uploads.
This solves a lot of issues:
1) When assembling new, potentially very large items, we don't have to sit and
spin evicting objects all at once. If there are 20 16k chunks in the tail and
we allocate a 1 meg item, the new item will evict one of those chunks …
> refactor chunk chaining for memory efficiency

- memcached.c
with -o hashpower=N allows you to statically presize the hash table. option will cause dangerous slowdowns if used improperly.
> Add -o no_hashexpand to disable hash expansion.

- scripts/memcached-automove-extstore
- slab_automove_extstore.c
- slabs.c
allows reassigning memory from global page pool to a specific class.
this allows simplifying the algorithm to rely on moving memory to/from
global, removing hacks around relaxing free memory requirements.
adds more comments and cleans up some code.
Edit:
- bug in script: removed "evictions happened" gating check but didn't replace with the pool_filled_once check that the internal version uses. should probably switch back to 'evictions' check for the external script.
> Slab automover fixes

- assoc.c
- assoc.h
- memcached.c
- trace.h
curr_items tracks how many items are linked in the hash table. internally to
the hash table, hash_items tracked how many items were in the hash table.
on every insert/delete, hash_items had to be locked and checked to see if th
table should be expanded. rip that all out, and call a check with the
once-per-second clock event to check for hash table expansion.
this actually ends up fixing an obscure bug: if you burst a bunch of sets
then stop, the hash table won't attempt to expand a second time until the
next insert. with this change, every second the hash table has a chance of
expanding again.
~2% perf improvement for sets against a single slab class. doesn't seem to help write scalability much. seems STATS_LOCK() needs more work :)
> remove redundant counter/lock from hash table

- linux_priv.c
Add missing `poll` call for the worker. Also make sure that we fail loudly if the seccomp setup fails.
Fixes #372
> Fix seccomp for lru-crawl

- doc/protocol.txt
- memcached.c
- t/misbehave.t
adds `-o drop_privileges` along with existing no_drop_privileges.
Feature is experimental, and causing some user pain: I'd forgotten about the
disable flag entirely, somehow.
Changing defaults (especially for a security feature) is not a typical thing
to do, but we should have done this from the start like all other features:
initially gated, then added to `modern`, then switched to default once mature.
> drop_privileges is no longer default if available.

- extstore.c
- extstore.h
- memcached.c
- storage.c
- storage.h
- t/binary-extstore.t
- t/chunked-extstore.t
- t/error-extstore.t
- t/extstore-jbod.t
- t/extstore.t
- t/lib/MemcachedTest.pm
With JBOD support, specifying disk space is also finally sane, but this deprecates -o ext_page_buckets immediately.
example:
`-o ext_path=/m/f/e1:500g,ext_path=/m/h/e2:500g,ext_path=/m/g/e3:1t:compact`
gives 500G worth of pages available for any use (default) split across two devices. a third device has 1TB of pages available only for compacted data. This can be used to mix and match different types or costs of drives, such as optane+SSD, or SLC|MLC+TLC drives.
as of this PR, bucket routing is disabled as that requires further fixes to the compaction algorithm. multiple devices may be added to the default free bucket just fine.
Some things don't make a ton of sense right now but given the production bottlenecks it's likely fine:
- just a big shared pool of IO threads.
- each type of page …
> Extstore performance boost and JBOD support

- items.c
- memcached.c
- memcached.h
- slabs.c
- storage.c
potential fix for #409 
not confident this is bug free.
some whackarse ARM platforms on specific glibc/gcc (new?) versions trip
SIGBUS while reading the header chunk for a split item.
the header chunk is unfortunate magic: It lives in ITEM_data() at a random
offset, is zero sized, and only exists to simplify code around finding the
orignial slab class, and linking/relinking subchunks to an item.
there's no fix to this which isn't a lot of code. I need to refactor chunked
items, and attempted to do so, but couldn't come up with something I liked
quickly enough.
This change pads the first chunk if alignment is necessary, which wastes
bytes and a little CPU, but I'm not going to worry a ton for these obscure
platforms.
> expand NEED_ALIGN for chunked items

- Makefile.am
- authfile.c
- authfile.h
- doc/protocol.txt
- memcached.c
- memcached.h
- t/ascii-auth.t
- t/authfile
- t/lib/MemcachedTest.pm
Loads "username:password\n" tokens (up to 8) out of a supplied authfile.
If enabled, disables binary protocol (though may be able to enable both
if sasl is also used?).
authentication is done via the "set" command. A separate handler is
used to avoid some hot path conditionals and narrow the code
executed in an unauthenticated state.
ie:
```
set foo 0 0 7\r\n
foo bar\r\n
```
returns "STORED" on success. Else returns CLIENT_ERROR with some
information.
Any key is accepted: if using a client that doesn't try to authenticate
when connecting to a pool of servers, the authentication set can be
tried with the same key as one that failed to coerce the client to
routing to the correct server. Else an "auth" or similar key would
always go to the same server.
kill -HUP'ing memcached causes it to …
> -Y [filename] for ascii authentication mode

- doc/protocol.txt
- memcached.c
- t/metaget.t
flags are now space deliminated. tokens are gone. if a flag has an
argument, it comes attached to the flag, ie:
`mg foo q T30 c`
"quietly update the TTL to +30 and return the CAS value"
response codes are updated slightly. If a value is requested:
`VA [size] [flags]\r\nvalue\r\nEN\r\n`
if a value is not requested:
`HD [flags]\r\nEN\r\n`
remove `EN\r\n` trailer from valid mg responses. VA is the status code, EN is
redundant. quiet mode elides the EN on miss.
meta-noop now has a dedicated `MN` status code for clarity.
fix bug in return data for `mg key\r\n`
updates tests for new changes.
code is shorter/simpler but it's a bigger change than I was hoping to
see at this point.
> Meta flagfix

- slabs.c
PR #524 speeds up the slab page mover for some situations: if an item
is expired, but not yet reaped (by a fetch, or LRU crawler), the slab
page mover unlinks the item, marks it as free, and doesn't mark the
loop as "Busy". If any items were marked as 'busy' (needing to be
freed, re-checked, or actively being used) the page mover will re-scan
all entries from the top.
With this change the re-scan becomes less likely.
The bug is in the check for chunked items. `ch` is only set if an
ITEM_CHUNK is detected. If ITEM_CHUNKED is instead detected we also
need to handle it with the full free routine. This was not done. This
frees the header item (CHUNKED), and then leaks all of the chunks
associated with it.
Getting into this situation is hard:
- have an expired chunked item in memory that the …
> slabs: fix crash in page mover

- doc/protocol.txt
- memcached.c
- t/metaget.t
ST/DE/HD all mean "okay". EX/NF/etc are already reused.
VA has different response parsing. EN/MN are specific.
future commands should be able to reuse most of these. In the odd case
new ones are added, clients would have to be updated. Generally they
shouldn't have to be.
> meta: make return codes generic

- Makefile.am
- cache.c
- cache.h
- configure.ac
- doc/protocol.txt
- memcached.c
- memcached.h
- t/conn-limits.t
- t/stats.t
- thread.c
allows specifying a megabyte limit for either response objects or read
buffers. this is split among all of the worker threads.
useful if connection limit is extremely high and you want to
aggressively close connections if something
happens and all connections become active at the same time.
missing runtime tuning.
> add separate limits for connection buffers

- doc/protocol.txt
- memcached.c
- memcached.h
- t/metaget.t
- thread.c
Commits fleshing out the TODO's from #546 
- fixes a refcount leak (oops!)
- some missing tests/cleanup
- refactors some core code
- adds the mode switch to metaset: set, add, cas, replace, append, prepend are now all just the `ms` command.
- adds meta arithmetic (`ma`) command.
> Meta protocol updates

- memcached.c
- memcached.h
- thread.c
Client connections were being closed and cleaned up after worker
threads exit. In 2018 a patch went in to have the worker threads
actually free their event base when stopped. If your system is strict
enough (which is apparently none out of the dozen+ systems we've tested
against!) it will segfault on invalid memory.
This change leaves the workers hung while they wait for connections to
be centrally closed. I would prefer to have each worker thread close
its own connections for speed if nothing else, but we still need to
close the listener connections and any connections currently open in
side channels.
Much apprecation to darix for helping narrow this down, as it presented
as a wiped stack that only appeared in a specific build environment on
a specific linux distribution.
Hopefully with …
> restart: fix rare segfault on shutdown

- memcached.c
sendmsg() on darwin doesn't like zero sized messages, apparently. Bails
out with "message too long". Don't think I intended to run the syscall
when there's nothing actually to send, anyway.
Should fix https://github.com/memcached/memcached/issues/681
> Fix TCP failure under OS X.

- crawler.c
- items.c
- items.h
- memcached.c
- memcached.h
- proto_bin.c
- proto_text.c
- slabs.c
- storage.c
- storage.h
- thread.c
This turns extstore's deferred IO queue into a more general subsystem, allowing other features to hook into it simultaneously. Pulling this work out of another feature I've been working on. 
This finishes abstracting extstore via the storage.c interfacing, which is now the only consumer of extstore.h. Moving storage.c to be a wrapper itself should allow more experimentation or dynamic backends. Finally, this removes the compile gating around the IO queue code.
Together this removes quite a lot of ifdef's, fixes layer violations, and fixes some naming to hopefully make the code more clear.
One more change added: io_pending_t now reserves space at the end. users cast it into a more specific structure, removing the extra allocations and storage-specific fields from io_pending_t.
> generalized deferred IO queue

- doc/protocol.txt
- memcached.c
- memcached.h
- proto_text.c
- t/metaget.t
PR follows the fixes for https://github.com/memcached/memcached/issues/546
Finally had a giant brain moment while wondering where to stash flag data for the set results: turns out wbuf has plenty of space! A small parser to replay some tokens was all that was needed. Now CAS can be atomically returned from a meta set.
There're a handful of fixes in here which should finalize the incompatible changes for meta.. anything new should be new.
> Meta command followups.

- memcached.c
Reported in #849 - this fixes copying a read buffer after freeing the
original read buffer.
This didn't matter for years since the cache code didn't touch the
buffer, but recently it can reuse the first 8 bytes as a pointer to the
internal freelist. Thus in some situations where large reads happen the
command can get corrupted, returning an unhelpful "ERROR" to the end
user.
> core: fix use-after-free for text multigets

- memcached.c
- memcached.h
- proto_proxy.c
- proto_proxy.h
- t/startfile.lua
Marks TODO/FIXME items that can be done after MVP/V1 status is achieved. This PR also attempts to address most of the non-v2 TODO/FIXME items.
"v2" just means "after v1". Not at all tied to a specific version or any
order.
This cuts us down from 170 items to... 80...
Most of what was marked v2 are optimizations or require some refactoring for future features. Most of what's left are missing error handling and obvious bugs/limitations. I'll fix all of these before doing more serious edge case testing, since after looking through them a lot of these are pretty obvious.
> proxy: audit TODO/FIXME lines. mark some for v2

- logger.c
- logger.h
- memcached.c
- memcached.h
- proto_proxy.c
- proto_text.c
- t/startfile.lua
More MVP grind:
- adds a bunch more stats to `stats proxy` - tracking how many of each type of command was received.
```
stats proxy
STAT user_example 0
STAT user_another 0
STAT cmd_mg 0
STAT cmd_ms 0
STAT cmd_md 0
STAT cmd_mn 0
STAT cmd_ma 0
STAT cmd_me 0
STAT cmd_get 0
STAT cmd_gat 0
STAT cmd_set 0
STAT cmd_add 0
STAT cmd_cas 0
STAT cmd_gets 0
STAT cmd_gats 0
STAT cmd_incr 0
STAT cmd_decr 0
STAT cmd_touch 0
STAT cmd_append 0
STAT cmd_prepend 0
STAT cmd_delete 0
STAT cmd_replace 0
END
```
- adds `watch proxycmds|proxyevents|proxyuser` watcher endpoints.
- adds `mcp.log()` lua interface to logging (lands in proxyuser)
- adds some logs to backend errors, these look like:
```
ts=1644553677.231725 gid=5 type=proxy_backend error=connecting ip=127.2.1.3 port=11213
ts=1644553677.231738 gid=6 …
```
> Proxy observability improvements

- Makefile.am
- devtools/clean-whitespace.pl
- logger.c
- md5.c
- md5.h
- proxy.h
- proxy_lua.c
- proxy_network.c
- proxy_ring_hash.c
- t/startfile.lua
- t/whitespace.t
this is ketama-based, with options for minor compat changes with major
libraries.
does _not_ support weights. The weights bits in the original ketama
broke the algorithm, as changing the number of points would shift
unrelated servers when the list changes.
this also changes backends to take a "name" specifically, instead of an
"ip address". Though note if supplying a hostname instead of an IP there
might be inline DNS lookups on reconnects.
> proxy: add ring_hash builtin

- proto_proxy.c
- proxy.h
- proxy_await.c
- proxy_request.c
- t/startfile.lua
There're a few usability features that bother me too much to go without in "v1"
- a hacky method of supporting noreply/quiet commands; I can see what would be bullet proof but will take time to get there.
- allow creating set requests from get responses. this is at least partly in now.
- _maybe_: get meta binary keys to work. Unfortunately this requires some fiddling as the key needs to be unpacked/repacked. The parser operates on const strings (as it must) so we would have to deal with binary keys from a layer higher.
- _maybe_: some extra functions for finding/editing meta tokens/flags
The meta routing tokens means we wouldn't necessarily have to examine binary keys at all, so for people trying to get every ounce of performance they can still avoid the transforms easily.
Everything past …
> Proxy feature roundup

- doc/protocol.txt
- logger.c
- logger.h
- memcached.h
- proto_proxy.c
- proto_text.c
- proxy.h
- proxy_await.c
- proxy_lua.c
- t/startfile.lua
Been experimenting with different logging interfaces. The `watch proxycmds` logger has a very limited view into the request context (mainly, it only has the response object and not the original request to compare to), but adds some other hard to get information (total length of a request cycle, etc). To get better logging with full context and some control lets hoist this into lua. It's also a crazy firehose so lets add some conditionals/sampling.
This adds `mcp.log_req(request, response, "detail")` and `mcp_log_reqsample(milliseconds, rate, allerrors, rq, rs, "detail")`. The idea is to add context from passing through a route function. See `t/startfile.lua`'s usage. Note that in startfile the reqlog is buried pretty low, but it could be the top level route as well. This means you can …
> proxy: mcp.log_req* API interface

- proxy.h
- proxy_lua.c
- proxy_request.c
- t/startfile.lua
- errors if a string value is missing the "\r\n" terminator
- properly uses a value from a response object
- allows passing in a request object for the value as well
- also adds r:vlen() for recovering the value length of a response
think this still needs r:flags() or similar?
TODO: a few more functions for this particular PR:
edit: note to self the characters are flags, arguments tokens, lol.
> proxy: mcp.request improvements

- proxy_request.c
- t/startfile.lua
returns (exists, previous_token)
optional second argument will replace the flag/token with supplied
flag/token, or nothing if "" is passed.
Done some limited testing and seems to work right. Apologies for not doing this in the original PR :)
@smukil
> proxy: req:flag_token("F", "Freplacement")

- logger.c
It dawns on me now that I should've been hinting or forcing the type at
all of the LOGGER_LOG endpoints to ensure they match the va_arg side on
logger.c. This patch initially swaps size_t's for int's so at least it's
using less complicated promotion rules.
Fixes a crash on centos 7 when logging sets via `watch mutations`
TODO
> log: fix obscure crashes due to size_t promotion

- memcached.c
- memcached.h
- proto_proxy.c
- proxy.h
- proxy_lua.c
- t/startfile.lua
- thread.c
`-l tag[asdfasdf]:0.0.0.0:11211`
in proxy:
`mcp.attach(mcp.CMD_ANY_STORAGE, routetop, "asdfasdf")`
If a third argument is given to mcp.attach, it will only route there if the client socket came from the matching listener socket's tag.
TODO
I _think_ I want a `noproxy` tag, but `mcp.attach(mcp.CMD_ANY, nil, "tag")` might be cleaner to implement so I'll have to check how hard it is first.
@smukil
> proxy: allow selecting top level routes based on listener tag

- items.c
- memcached.h
- proto_text.c
- slab_automove_extstore.c
- storage.c
extstore has a background thread which examines slab classes for items
to flush to disk. The thresholds for flushing to disk are managed by a
specialized "slab automove" algorithm. This algorithm was written in
2017 and not tuned since.
Most serious users set "ext_item_age=0" and force flush all items. This
is partially because the defaults do not flush aggressively enough,
which causes memory to run out and evictions to happen.
This change simplifies the slab automove portion. Instead of balancing
free chunks of memory per slab class, it sets a target of a certain
number of free global pages.
The extstore flusher thread also uses the page pool and some low chunk
limits to decide when to start flushing. Its sleep routines have also
been adjusted as it could oversleep too easily.
A few …
> extstore: make defaults more aggressive

- proto_proxy.c
- proxy_await.c
- proxy_lua.c
- proxy_network.c
- vendor/mcmc/example.c
- vendor/mcmc/mcmc.c
- vendor/mcmc/mcmc.h
upstream fixes: mcmc would return OK to garbage responses, which was
probably causing issues in the past.
This does remove the MCMC_CODE_MISS and replace it with MCMC_CODE_END.
Updated the commit a bit more: status is now either `MCMC_OK` or `MCMC_ERR` and resp.code always has the detail. I feel this is slightly cleaner overall.
I also didn't pull in the tests/* dir from mcmc since that's not really necessary yet.
@smukil - tagging for interest
> proxy: update mcmc and calling conventions

- proxy.h
- proxy_await.c
- proxy_lua.c
returns early on a hit, else waits for N non-error responses.
> proxy: add mcp.await FASTGOOD flag

- assoc.c
- crawler.c
- extstore.c
- items.c
- logger.c
- memcached.c
- memcached.h
- proto_proxy.c
- proxy_config.c
- slabs.c
- storage.c
- thread.c
allow users to differentiate thread functions externally to memcached. Useful for setting priorities or pinning threads to CPU's.
Pretty trivial outside of needing to duplicate the function for extstore. I don't have instances handy to test BSD/OBSD/etc so I've left those forms out for now so I don't accidentally break builds. Any user with such a platform should feel free to submit a tested patch too.
I may or may not move the function to a new header file before merging. I might wait because I've been doing some slow audits and might want to structure it differently if I can find more common code to pull out.
> core: give threads unique names

- proxy.h
- proxy_await.c
- proxy_lua.c
- proxy_network.c
- t/startfile.lua
mcp.await(request, pools, 0, mcp.AWAIT_BACKGROUND) will, instead of waiting on any request to return, simply return an empty table as soon as the background requests are dispatched.
This works by creating a dummy IO object that immediately gets returned to the worker thread once the rest of the IO's are queued properly.
> proxy: add mcp.AWAIT_BACKGROUND

- proxy.h
- proxy_network.c
1) more IOV's per syscall
2) if a backend got a large stack of pending IO's + continual writes the
CPU usage of the IO thread would bloat while looping past already
flushed IO objects.
> proxy: IO thread performance improvements

- proxy.h
- proxy_config.c
- proxy_lua.c
- proxy_network.c
- vendor/mcmc/mcmc.c
A backend's connection object is technically owned by the IO thread
after it has been created. An error in how this was done lead to invalid
backends being infinitely retried despite the underlying object being
collected.
This change adds an extra indirection to backend objects: a backend_wrap
object, which just turns the backend connection into an arbitrary
pointer instead of lua memory owned by the config VM.
- When backend connections are created, this pointer is shipped to the
IO thread to have its connection instantiated.
- When the wrap object is garbage collected (ie; no longer referenced by
any pool object), the be conn. pointer is again shipped to the IO
thread, which then removes any pending events, closes the sock, and
frees data.
TODO:
There may be some conditions lurking …
> proxy: fix lifecycle of backend connections

- proxy.h
- proxy_request.c
had an API bug where updating a token and then requesting it again returns the previous token. Also have other branches which require use of the flattened request.
I was originally doing this using a lot of lua but just copying the string a few times has some better properties:
1) should actually be faster with less lua + fewer allocations 
2) can be optimized to do minimal copying (avoid keys, append new flags, etc)
3) might be optimized to avoid re-parsing (or do minimal re-parsing) in some cases.
TODO:
> proxy: iterate modified request handling

- memcached.c
- memcached.h
Allow freeing client response objects without the client object. Clean some confusing logic around clearing memory. Also exposes an interface for allocating unlinked response objects.
Mostly trivial patch that just changes more `*c->thread` to `*t`, but also removes a difficult to read memset and cleans the code a bit. Easy to verify.
> core: remove *c from some response code

- proto_proxy.c
- proxy.h
- proxy_await.c
- proxy_lua.c
We were duck typing the response code for a coroutine yield before. It would also pile random logic for overriding IO's in certain cases. This now makes everything explicit and more clear.
> proxy: clean logic around lua yielding

- proto_proxy.c
- proxy.h
- proxy_await.c
- proxy_network.c
- specifically the WSTAT_DECR in proxy_await.c's return code could potentially use the wrong thread's lock
This is why I've been swapping c with thread as lock/function arguments all over the code lately; it's very accident prone.
Am reasonably sure this causes the deadlock but need to attempt to verify more.
- Also fixes a bug I found while trying to reproduce the stats deadlock. See commit message for details there.
> proxy: fix stats deadlock and mismatched responses

- proto_proxy.c
- proxy.h
- proxy_lua.c
- proxy_network.c
- t/proxyconfig.lua
- t/proxyconfig.t
ie:
```
local b1 = mcp.backend({ label = "b1", host = "127.0.0.1", port = 11511,
connecttimeout = 1, retrytimeout = 0.5, readtimeout = 0.1,
failurelimit = 11 })
```
... to allow for overriding connect/retry/etc tunables on a per-backend basis. If not passed in the global settings are used.
TODO:
Note:
- The tradeoff: previously it was possible to change `mcp.backend_read_timeout` and similar without the proxy internally recreating any backends, but now modifying the global settings will re-create all backend objects. This makes reload slower when timeouts are adjusted; realistically this isn't done often and reload is still generally fast.
- If you are _not changing the global settings_, but _only changing individual backend overrides_, only those overridden backends will be recreated on …
> proxy: add mcp.backend(t) for more overrides

- proto_proxy.c
- t/proxyunits.lua
- t/proxyunits.t
Response object error conditions were not being checked before looking at the response buffer. If a response was partially filled then the backend timed out, a partial response could be sent intead of the proper backend error.
@feihu-stripe - not what we were looking for but a bug I hadn't followed up on from a few weeks ago.
> proxy: fix partial responses on backend timeouts

- logger.c
- logger.h
- proxy_network.c
- t/proxyunits.t
Errors like "trailing data" or "missingend" or etc are only useful if you're in a debugger and can break and inspect. This adds detail in uriencoding into the log message when applicable.
@feihu-stripe 
TODO
Also just very tired right now and don't want to drop this directly into `next` so I can double check it tomorrow.
> proxy: add read buffer data to backend errors

- proxy_network.c
- t/proxyunits.t
If the backend handler reads an incomplete response from the network, it changes state to wait for more data. The want_read state was considering the data completed if "data read" was bigger than "value length", but it should have been "value + result line".
This means if the response buffer landed in a bullseye where it has read more than the size of the value but less than the total size of the request (typically a span of 200 bytes or less), it would consider the request complete and look for the END\r\n marker.
This bug has been... here forever.
@feihu-stripe
> proxy: fix "missingend" error on reading responses

- proxy.h
- proxy_lua.c
- proxy_network.c
- t/proxyconfig.t
The event handling code was unoptimized and temporary; it was slated for a rewrite for performance and non-critical bugs alone. However the old code may be causing critical bugs so it's being rewritten now.
Fixes:
- backend disconnects are detected immediately instead of on the next time they are used.
- backend reconnects happen _after_ the retry timeout, not before
- use a persistent read handler and a temporary write handler to avoid constantly calling epoll_ctl syscalls for potential performance boost.
- avoids overwriting the read timeout when many requests are being queued for the same non responsive backend
Commit in progress, still hunting some other related timing bugs that seem to still happen.
> proxy: redo libevent handling code

- Makefile.am
- proto_proxy.c
- proxy.h
- proxy_internal.c
- proxy_lua.c
Still pending some work. Change has been minimized by upstreaming pre-requisite work.
This change adds a lua command:
```
local res = mcp.internal(r)
```
... which will dispatch the request using the embedded local cache in the proxy. Works with extstore enabled.
This was always the other half of the big plan for embedding the proxy into memcached: one was code reuse, the other was "Swiss army chainsaw" for cache flexibility. I'll get into all the wonderful benefits when this is closer to merge. Some ideas:
- Convert any existing pool of memcached's into proxies. Serve gets from local cache, replicate sets to redundant caches. Backhaul misses, etc.
- Convert legacy client requests into new or adjusted commands. IE: `incr foo 1` could change into a meta arithmetic command with the …
> Proxy: mcp.internal(r) for accessing local cache.

- crawler.c
- memcached.h
- proto_text.c
LRU crawler in per-LRU mode only flushes the write buffer to the client socket while not holding important locks. The hash table iterator version of the crawler was accidentally holding an item lock while flushing to the network. Item locks must NOT be held for long periods of time as they will cause the daemon to lag.
Originally the code used a circular buffer for writing to the network; this allowed it to easily do partial write flushes to the socket and continue filling the other half of the buffer.
Fixing this requires the buffer be resizeable, so we instead use a straight buffer allocation. The write buffer must be large enough to handle all items within a hash table bucket.
Hash table buckets are _supposed_ to max out at an average depth of 1.5 items, so in theory it should never …
> crawler: don't hold lock while writing to network

- proto_proxy.c
- proxy_internal.c
- proxy_network.c
- t/proxyinternal.lua
- t/proxyinternal.t
- Refcount leak on sets
- Move the response elapsed timer back closer to when the response was processed as to not clobber the wrong IO object data
- Adds start of unit tests
Requests will look like they run a tiiiiny bit faster than they do, but I need to get the elapsed time there for a later change.
TODO
> proxy: mcp.internal fixes and tests

- doc/protocol.txt
- logger.c
- memcached.c
- memcached.h
- proto_bin.c
- proto_text.c
- proxy_internal.c
- t/metaget.t
- thread.c
Sending 's' flag to metaset now returns the size of the item stored. Useful if you want to know how large an append/prepended item now is.
If the 'N' flag is supplied while in append/prepend mode, allows autovivifying (with exptime supplied from N) for append/prepend style keys that don't need headers created first.
These flags all pre-existed and their meanings are re-used. So fancy.
TODO:
> meta: N flag changes append/prepend. ms s flag.

- memcached.h
- proto_proxy.c
- proxy.h
- proxy_await.c
- proxy_config.c
- proxy_lua.c
- proxy_network.c
- proxy_request.c
- proxy_ustats.c
- t/proxyconfig.lua
- t/proxyconfig.t
- t/proxyunits.lua
- t/startfile.lua
Adds two limiters:
- mcp.active_req_limit(count) - number of concurrent active requests
- mcp.buffer_memory_limit(kilobytes) - Amount of kilobytes of buffer memory used for request and response values for the proxy.
Not quite as straightforward as I hoped. Needed to make access to mcp.* functions more strict for the config and route routines; you can no longer call config functions from routes and vice versa.
Performance should be good; the counters are per-worker-thread and uses an uncontested mutex to cover. I wanted to go nuts with atomics but that should be a distinct change.
Caveat:
- There is a "hole" for request accounting where the memory can't be accounted for until after it's fully read from the network. More restructuring is required; this is probably fine for the scope of this …
> Proxy limiters

- proto_proxy.c
- t/proxyunits.t
If a client sends multiple requests in the same packet, the proxy would reverse the requests before sending them to the backend. They would return to client in the correct order because top level responses are sent in the order they were created.
In practice I guess this is rarely noticed. If a client sends a series of commands where the first one generates a syntax error, all prior commands would still succeed.
It would also trip people up if they test pipelining commands as read-your-write would fail as the write gets ordered after the read.
Did run into this before, but I thought it was just the ascii multiget code reversing keys, which would be harmless as the whole command has to complete regardless of key order.
---
I'm creating a PR for this but it will be short lived, so there can …
> proxy: fix reversal of pipelined backend queries

- proto_proxy.c
- proxy.h
- proxy_lua.c
- proxy_network.c
- t/proxyunits.lua
- t/proxyunits.t
- vendor/mcmc/mcmc.c
- vendor/mcmc/mcmc.h
Cleans up logic around response handling in general. Allows returning
server-sent error messages upstream for handling.
In general SERVER_ERROR means we can keep the connection to the backend.
The rest of the errors are protocol errors, and while some are perfectly
safe to whitelist, clients should not be causing those sorts of errors
and we should cycle the backend regardless.
TODO:
At some point I'll either merge code/resp in mcmc or figure out some better way of representing that data, as they do overlap.
> proxy: overhaul backend error handling

- proto_proxy.c
The client connection state machine loops through a few states when handling pipelined requests.
To start:
conn_waiting -> conn_read -> conn_parse_cmd (execution)
After conn_parse_cmd, we can enter:
conn_nread (read a mutation payload from the network) -> conn_new_cmd or directly: conn_new_cmd
conn_new_cmd checks the limit specified in -R, flushing the pipeline if we exceed that limit. Else it wraps back to conn_parse_cmd
The proxy code was _not_ resetting state to conn_new_cmd after any non-mutation command. If a value was set it would properly run through nread -> conn_new_cmd
This means that clients issuing requests against a proxy server have unlimited pipelines, and the proxy will buffer the entire result set before beginning to return data to the client. Especially if requests are …
> proxy: fix bug ignoring -R setting for proxy reqs

- Makefile.am
- proxy.h
- proxy_lua.c
- proxy_ratelim.c
- t/proxyratelim.lua
- t/proxyratelim.t
See t/proxyratelim.lua for usage.
Trivial interface with good enough performance for some situations. Allows having an arbitrary number of limiters (ie; one per path) by creating more objects.
trivial. going to let it sit overnight then merge to staging after a self review.
> proxy: add mcp.ratelim_tbf({})

- proxy.h
- proxy_lua.c
- proxy_network.c
- t/proxyconfig.lua
- t/proxyconfig.t
Starts backend in a "bad" state, so any attempt to access it will result in "SERVER_ERROR backend failure".
The only times a backend's bad flag can be removed is on a successful connection attempt. So all we need to do is avoid fully setting up or tearing down the backend and starting it marked bad.
TODO:
> proxy: mcp.backend({ down = true }) option

- logger.c
- logger.h
- proto_proxy.c
- proxy.h
- proxy_lua.c
- proxy_network.c
- t/proxyantiflap.lua
- t/proxyantiflap.t
This change allows detecting if backend servers are "flapping" when
given traffic. This means they connect, validate, and can answer
responses, but under normal traffic workloads they break. This could be
due to noisy neighbor issues, network congestion, bugs, etc.
This change also updates an existing setting:
mcp.backend_retry_timeout(seconds), is now:
mcp.backend_retry_waittime(whole seconds)
... this setting is the amount of time to hold a backend in a "bad"
state, before attempting to reconnect again, once it has exceeded its
consecutive failure limit. It must be at least one second and is
specified as whole seconds.
The new tunables are:
mcp.backend_flap_time(seconds) (default: 0)
- Once a backend is successfully connected, if this much time does not
pass before it throws a …
> proxy: backend antiflap detection.

- proxy.h
- proxy_request.c
- t/proxy.t
A bunch of the parser assumed we only had \r\n, but I didn't actually have that strictness set. Some commands worked and some broke in subtle ways when just "\n" was being submitted.
I'm not 100% confident in this change yet so I'm opening a PR to stage it while I run some more thorough tests.
> proxy: fix off-by-one if \r is missing

- proxy_config.c
Missed two lines from the lru crawler init routine, because I'm an idiot who didn't abstract the start function.
The dance to wait for a thread to start isn't trivial. It's done here via:
main thread:
- lock mutex
- create new thread while holding lock
- go into condition wait, which releases the lock
new thread:
- start function
- lock mutex
* at this point, we are blocked until main thread starts waiting on the condition.
- send condition signal.
* at this point the main thread _would_ wake up, but we are still holding the lock.
- start our main routine, go into condition wait, which releases the lock
main thread:
- wake up from the condition wait, with the lock held.
- unlock the mutex.
now the main thread can continue while being confident the side thread is waiting for work properly.
> proxy: fix race condition in first load

- Makefile.am
- memcached.c
- memcached.h
- proto_proxy.c
- proto_proxy.h
- proto_text.c
- proxy.h
- proxy_await.c
- proxy_internal.c
- proxy_lua.c
- proxy_luafgen.c
- proxy_request.c
- t/lib/MemcachedTest.pm
- t/proxyfuncgen.lua
- t/proxyfuncgen.t
- t/proxyintext.lua
- t/proxyintext.t
- t/proxyrouter.lua
- t/proxyrouter.t
- t/proxytags.lua
- t/proxytags.t
See #1085 for development history
See t/proxyfuncgen.lua for documentation on API changes.
See also https://github.com/memcached/memcached/wiki/Proxy
This change revolves around holding context during request execution. Previously the lua context simply "floated", being carried with a backend IO request when necessary and resumed during a later callback. It was not possible to know things for the full duration of a request. It was also not possible to hold references for the full duration of a request.
For example, previously when lua executes a request against a single pool (pool(req) syntax), the pool and request objects are held in the coroutine's execution stack, then the coroutine is suspended. This prevents the pool from being garbage collected while the request executes. Nothing …
> proxy: lua API version 2

- proxy.h
- proxy_config.c
- proxy_lua.c
- proxy_ratelim.c
- t/proxyratelim.lua
- t/proxyratelim.t
If created during mcp_config_pools() and then passed into mcp_config_routes(), utilizes a centralized rate limiter.
TODO:
waiting a few days then more code review/testing and merge.
> proxy: add global rate limiter

- proxy.h
- proxy_config.c
- proxy_luafgen.c
- t/proxyslotcache.lua
- t/proxyslotcache.t
Any allocated request context would stay in memory attached to its function generator until the next reload, which would replace the function generators. A replaced fgen would eventually run out of attach references and cleanup itself, removing all rcontexts.
A one-time burst of concurrent request contexts would thus take up memory forever. With this change we use an easing function to slowly free unneeded request contexts.
This can help for both memory usage scenarios and instances where the GC is still used in the request path and tail latency can become poor.
TODO:
There aren't tests monitoring `stats proxyfuncs` so something specific to this is probably necessary. We need to validate it across reloads and during various easing scenarios after temporary concurrent blasts.
Should be …
> proxy: allow early freeing rcontexts

- memcached.h
- proto_proxy.c
- proto_proxy.h
- thread.c
Tries to move the GC run from inline requests to outside of requests.
Passes tests but not benchmarked yet. Might not be interacting properly with the "GC Pause" tunable on when to actually kick off a GC.
Also avoids running GC during code reload and ignores memory allocated during code reload.
TODO:
> Proxy lua GC tuning

- extstore.c
- extstore.h
- memcached.c
- memcached.h
- storage.c
- t/binary-extstore.t
- t/extstore-overdel.t
- t/extstore-tiered.t
- t/extstore-tiered2.t
earlier commits added the concept of free_buckets and were able to run
simple tests of tiered device storage.
this commit rewrites the way compaction is handled in extstore to be more efficient (write less), and enables concepts of tiered storage: items can be moved to different files/devices depending on their status.
run with: `ext_path=/path/f1:64m,ext_path=/path2/f2:128m:compact`
creates a 64m file for "default" pages and a 128m file for compacted
pages. Also works with 'chunked' and 'lowttl'
This also adds buckets `old` and `coldcompact`. IE:
`ext_path=/path/f1:64m,ext_path=/path2/f2:128m:old`
If `old` exists and we run out of disk space in the main buckets, items are moved from their original location to the device holding the `old` file. This is useful if you have a load/reload …
> extstore: tiered storage

- configure.ac
- extstore.c
- thread.c
Fix the following build failure with uclibc-ng raised since version 1.6.18 and https://github.com/memcached/memcached/commit/875371a75cbf1f92350de2d1fa0fae4a35ed572b:
```
/home/buildroot/autobuild/instance-2/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: memcached-thread.o: in function `thread_setname':
thread.c:(.text+0xea2): undefined reference to `pthread_setname_np'
```
Fixes:
- http://autobuild.buildroot.org/results/e856d381f5ec7d2727f21c8bd46dacb456984416
> fix build on uclibc-ng

- proto_proxy.c
- proto_proxy.h
- proto_text.c
- proxy.h
- proxy_network.c
- t/lib/MemcachedTest.pm
- t/proxybestats.lua
- t/proxybestats.t
stats command intended for backend state information.
so far just outputs "bad_label" [count] for each backend currently marked bad. The count is the number of backend objects marked bad.
If in "per worker thread mode" (default) if all workers recognize the backend as down, the count will be the same as the number of worker threads. If the IO thread is in use it would be 1.
If a backend has normal status, it is not included in the output.
TODO:
> proxy: `stats proxybe` to show bad backends

- proto_proxy.c
- proxy.h
- proxy_config.c
- proxy_lua.c
- t/proxycron.lua
- t/proxycron.t
Adds a system for periodically running functions in the configuration thread. These crons may also signal to reload the configuration after they run. IE: you may shell out or run a module to fetch and download new json data, then reload the configuration.
mcp.register_cron("name",
{ every = seconds, func = function()
print("cron running")
end })
Also accepts { rerun = false } to run the cron once after a reload. Can be used to check something after a reload has run, or simply issue a reload after an exact amount of time since the previous reload finished.
Crons that are not seen after a config reload are unloaded. IE: the only crons that may run must have been registered during the last configuration reload.
If a cron is overwriting itself, and the 'every' period has not changed, it will …
> proxy: config thread cron functions

- proto_proxy.c
- proxy.h
- proxy_lua.c
- proxy_luafgen.c
- t/proxyrctxtimeout.lua
- t/proxyrctxtimeout.t
give request contexts the ability to time out on wait operations. this allows moving along the logic without cancelling in flight requests or resetting backends.
TODO:
This is due to the API still missing a few variants of `wait` (ie: enqueue and wait cond, wait and return "best", etc). Internally the `_timeout()` version is identical except for the extra argument parsing. So with `_timeout()` variants we'd have like ten wait functions...
not feeling great today so finishing this tomorrow.
> proxy: wait timeout API

- doc/protocol.txt
- proto_text.c
- proxy_internal.c
- t/metaget.t
If `md` is given the `I` flag _and_ `x` flags it will mark stale and
remove the value, but leave the item.
This allows the user to create a tombstone of a previous value with a
new TTL.
TODO:
> meta: md with I and x removes value

- memcached.c
- memcached.h
- proto_proxy.c
- proto_proxy.h
- proxy_lua.c
- storage.c
- storage.h
- t/proxyintstats.lua
- t/proxyintstats.t
Allow accessing server stats from the configuration thread (useful for crons, checking start args, etc). Does not support cachedump or detail.
Returns a table of the results. The results are thus unordered.
---
Much smaller code change than I expected, though I have to rely on an unfortunate global variable until some further refactoring of the stats commands.
TODO:
It's not hard to parse the ordered outputs (items, conns, slabs) since you can just loop up until the numbers miss, but it might be more convenient to be able to loop the table directly sometimes. It would add a lot of code, I think?
How would that work? Detect :'s and make a sub-table until the # stops matching or the : goes away?
> proxy: `mcp.server_stats(subcmd)`

- memcached.h
- proto_proxy.c
- proxy_internal.c
- proxy_luafgen.c
- proxy_network.c
- t/proxyinternal.t
If a lua function schedules extra requests after an initial set of requests, we need to use a workaround to ensure the second set of requests is actually submitted to the proxy backends.
This workaround was in the wrong place. If connections are being cut and reconnected between batches of requests it's possible for the workaround to trigger on a connection object that has since moved to another thread.
This patch tightens up the workaround to run before the client connection has a chance to resume.
---
TODO:
> proxy: fix race condition leading to hang

- proto_proxy.c
- proxy_lua.c
If running a fetch request without returning the result upstream to the user, a successfully fetched item would leak its reference.
> proxy: fix refcount leak in mcp.internal()

- proto_proxy.c
- proxy.h
- proxy_lua.c
- proxy_network.c
- t/proxydepthlim.lua
- t/proxydepthlim.t
If a backend has a queue depth limt over this amount, fast-fail any further requests.
A global parallel request limit can mean a single slow or overloaded backend causes the entire proxy to stop working. As a first layer of defence the depth for a particular backend should be capped.
TODO:
~- [ ] might add a counter for failed-due-to-bad while I'm in here.~
~- [ ] might also add a tunable for fast-failing while be is connecting/validating. been meaning to do that forever.~
delaying further TODO's until after the TLS work is in testing.
> proxy: add mcp.backend_depth_limit(int)

- Makefile.am
- configure.ac
- proto_proxy.c
- proxy.h
- proxy_lua.c
- proxy_network.c
- proxy_tls.c
- proxy_tls.h
WIP. Connects, handshakes, and routes requests as of this commit. Needs further work before mergeable.
TODO:
TODO MAYBE:
ETA: maybe a week? It does currently work, so it might not take long to finish.
GOALS:
- Enable TLS on a global or per-backend basis. Propagate errors properly.
- Minimize `#ifdef` soup and testing burden by using a shim for accessing OpenSSL and leaving some TLS related code always compiled in. The shim nulls itself out if TLS support is not compiled in.
FOR FUTURE PR's:
- Load and reload client certificates/keys
- Peer certificate validation
- sessions / session tickets
- maybe: sidethread for handshake calcs (if not reusing a session)
- io_uring preparedness.
I'm separating certificate work out of this PR so I can keep the change focused for initial validation. Tired …
> proxy: backend TLS support

- proxy.h
- proxy_luafgen.c
- t/proxyrouter.lua
- t/proxyrouter.t
Allows specifying a commandmap on a router as well as a map and default route. Lookup order is:
- Check map, if entry in map, check that
- If none matched, check fallback command map
- If nothing matched, return default route handler if exists
Also removes the router struct from the funcgen object, saving 32 bytes and letting me extend the size of the router struct without bloating every allocated fgen. This will later allow inlining the lookup map into the router struct for a lookup speedup.
> proxy: router refactor and cmap fallback

- proto_proxy.c
- proxy.h
- proxy_config.c
- proxy_ustats.c
- t/proxyustats.t
If a ustat changes name for the same index, its value is reset to 0.
Cleans up some confusing code around how ustats are handled; the global ctx and worker threads now use different structures with different intent, instead of different sides of the same struct.
Also reorders the entries in the global ctx so the most frequently accessed ones are clustered toward the front of the struct.
> proxy: ustats internal refactor

- memcached.c
- memcached.h
- t/lib/MemcachedTest.pm
- t/ssl_ports.t
- tls.c
- tls.h
For the -l arguments with 'notls:ip:port' we now have 'btls:ip:port' and 'mtls:ip:port'
'btls' disables peer certificate verify on this listener, if it was enabled globally by `ssl_verify_peer`.
'mtls' enables peer certificate verify on this listener. This is the same as setting ssl_verify_peer to 'require'
NOTES:
This is basically the line before needing to move to a more complex system. IE: if a user sees this and wants to have different server certs per listener that would require a completely new feature.
TODO:
The tests for peer verification are pretty basic, so I want to spend a little effort to see if it's worth improving that.
If a peer cert verify fails it _should_ show up as an error in `watch connevents` already.
I'm also trying to figure out if I can add a counter for times …
> tls: per-listener cert validation

- Makefile.am
- proxy.h
- proxy_inspector.c
- proxy_internal.c
- proxy_lua.c
- proxy_network.c
- proxy_request.c
- proxy_result.c
- t/proxyins.lua
- t/proxyins.t
- t/proxyrequest.lua
- t/proxyrequest.t
- t/proxyunits.lua
- t/proxyunits.t
- vendor/mcmc/example.c
- vendor/mcmc/mcmc.c
- vendor/mcmc/mcmc.h
Adds interfaces for inspecting request and response objects without or with minimal allocations and argument checking overhead.
Simple extensions:
```lua
-- directly converts token at offset n into a lua integer. avoids string -> num round tripping
-- used for standard ascii commands (ie; set)
int = req:token_int(n)
```
```lua
-- returns "exists", then an int conversion of a token directly.
-- if the flag exists but the token could not be converted to a number, returns 'true, nil'
bool, int = req:flag_token_int("f")
```
```lua
-- Replaces the flag and associated token with blank spaces. This removes the flag without fully
-- rewriting the result.
res:flag_blank("O")
```
```lua
-- inspectors are pre-configured objects that can be applied to a request or result to make
-- one or more …
```
> Proxy API: req/res accessors and inspector object

- proxy.h
- proxy_lua.c
- proxy_luafgen.c
- tls.c
- tls.h
Returns a string copy of the TLS peer CN entry. Returns nil if none exists or unable to parse the certificate.
---
Untested but compiles.
TODO:
> proxy: str = rctx:tls_peer_cn()

- Makefile.am
- proxy.h
- proxy_lua.c
- proxy_luafgen.c
- proxy_mutator.c
- proxy_result.c
- t/proxymut.lua
- t/proxymut.t
Usage is similar to inspector object in #1162
`status = mut(destination, src, src, src, src)`
IE: based on configured steps, takes arguments for assembling the new request or response string
`status = mut(new_res, "HD", 33, another_result)`
On the "config" side an argument is referred to by an `idx` parameter. IE: in the above example "HD" would be in `idx = 2`, as the first user parameter. 33 would be 3, etc. Multiple steps can refer to the same idx. ex: pulling a key and some flags from the same request object in idx 2.
Some steps can also refer to multiple input arguments. IE: take a range of arguments and combine them.
Complete basic example:
```lua
-- basic; no flags or outside info
local mut_mgreq = mcp.req_mutator_new(
{ t = "cmdset", cmd = "mg" },
{ t = "keyset", str = "override" …
```
> Proxy req/res mutator object

- Makefile.am
- memcached.c
- proxy_config.c
- t/proxyroutelib.lua
- t/proxyroutelib.t
`-o proxy_config=routelib` will use the binary-distributed routelib library
Not thrilled about including a mystery data file in the vendor directory.
Don't want to make `xxd` part of the build requirements for proxy either?
Maybe the plan is:
- Start with this so we have something.
- Include the routelib.lua file in here too.
- Soon write my own minimal bin2c that lives in the tree somewhere
- Remove the distributed .h and somehow get the build system to build and run the bin2c first
- Have the .h as a build artifact.
You can just ld files but it's not portable either.
TODO:
> proxy: embed routelib

- proxy.h
- proxy_luafgen.c
- proxy_mutator.c
- t/proxymut.lua
- t/proxymut.t
The goal of this PR is to stabilize the mutator object for production use. Additional steps will most likely be in future PR's.
Tasks:
Result handling might have to wait for another PR, pending fixes to mcmc to use relative offsets vs full fixed pointers. This is causing us to need to re-parse results every time we look at them.
Delayed:
> Proxy mutator object continuation

- proto_proxy.c
Updating the proxy GC default ratio from `1.9` to `2.0` to reduce its aggressiveness. This adjustment aligns with the GC algorithm fix introduced in [commit d164eb1](https://github.com/memcached/memcached/commit/d164eb151af58f3835b63a83bb38e8d42892e669) and has been verified to perform well during tests.
> Changing the proxy GC default ratio from 1.9 to 2.0

- memcached.c
- proto_proxy.c
- proxy.h
- proxy_luafgen.c
- proxy_network.c
Uses a shorter return path for completed IO objects, resulting in 5%+ performance bump.
Also cleans up some of the remaining hack code from before the IO subsystem fix.
---
TODO:
> proxy: speed up per-worker backend IO

- proxy.h
- proxy_internal.c
- proxy_lua.c
- proxy_luafgen.c
- t/proxyinternal.lua
- t/proxyinternal.t
- t/proxyinternal2.lua
- t/proxyinternal3.lua
Replaces `res = mcp.internal(req)` with the standard V2 API flow. Create a handle for an fgen using `mcp.internal_backend` as an argument, then call wait against it like a normal pool.
Terrible thought: am I naming this wrong?
`mcp.internal_backend` -> `mcp.internal_pool`
because you can't actually add it as a pool backend. it _could_ be nice if that worked but I think it would get people into more trouble than it's worth.
> proxy: internal backend for V2 API

- logger.c
- logger.h
- proto_proxy.c
- proxy.h
- proxy_internal.c
- proxy_lua.c
- proxy_luafgen.c
- proxy_network.c
- t/proxyfuncgen.lua
- t/proxyfuncgen.t
- t/proxyinternal.lua
- t/proxyinternal.t
- t/proxyunits.t
Options similar to mcp.log_reqsample() are applied to responses as they're read off the network.
Can be a lot faster than relying on callbacks to do logging, if you're not doing logging inline with a route handler. Also simpler in some cases (ie routelib).
This code also leverages the removal of V1 and cuts 250 bytes from every res object, resulting in less memory used per "request slot", and an extra minor speedup on _all_ requests from less time in memset and not copying the backend host/port onto every response.
TODO:
> proxy: per-backend automatic logging

- crawler.c
- util.c
- util.h
Unrolls the sprintf used for `lru_crawler metadump` since it is a hot path. Increases dump speed with no crawler sleep by 30%.
Also adds the disk page and disk page offset via `ext_page` and `ext_offset` if the item is on disk.
Credit to @hemal-shah for the idea on dumping extstore information.
> crawler: speedup and extstore info

- memcached.c
- proto_proxy.c
- t/proxyfuncgen.t
- t/proxyms.lua
- t/proxyms.t
- IO objects are enqueued per-worker-thread since a refactor in ec1fb560
- If a set payload is being read off the network but the read gets EAGAIN, _and_ there are already pending IO objects on the connection, the worker thread will execute the pending IOs
- The worker resume code did not check for conn_nread state and would resume the connection's state machine if those IO's completed before the conn_nread state completes.
- The connection state is now corrupt and will both leak memory and throw parsing errors.
This is a one-line fix to avoid resuming the state machine if we were in conn_nread state, as well as avoiding finalizing a connection from the conn_closing state if there are pending suspended responses.
TODO:
Have some minimized unit tests that all fail without fix and run with …
> core: fix pipelined set failures on pending reads

- memcached.c
Fixes https://github.com/memcached/memcached/issues/799
Closes https://github.com/memcached/memcached/issues/1220
See https://github.com/memcached/memcached/issues/1220#issuecomment-3109594827 and following comments for testing that led to this discovery :partying_face:
> Fix typecast on setting stop_time during restart

- proxy_mutator.c
- t/proxymut.lua
- t/proxymut.t
- lets mutator use results from mcp.internal calls.
- if flagcopy's index is a nil, does not set the flag at all.
- adds very limited flagcopyall that can copy the result line from a result object. can't do requests or selectively exempt flags.
> proxy mutator minor improvements
